### ISSUE TITLE
Create public dashboards

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Insights#38]
As we improve the .NET ecosystem we need to understand the adoption of new features and best practices. This will help us make informed engineering investments. This could be done using public Power BI dashboards of NuGet insight's data. For example:

![image](https://user-images.githubusercontent.com/737941/122653873-82385d00-d0fc-11eb-9789-1bf0e74965dd.png)

Microsoft employees can play with my dashboard prototype here: https://msit.powerbi.com/groups/me/reports/0c673992-f323-44b5-be81-f8e75afbaee0/ReportSection24621557a494a04b6f43

This is similar to the ASP.NET Core team's public Power BI dashboards: https://aka.ms/aspnet/benchmarks

We can use Power BI's data refresh feature to keep these dashboards up-to-date: https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#data-refresh

**Comment by joelverhagen** [comment]
Good stuff. Nice job finding the prior art. This seems perfect.

For the dashboards, what do you think about focusing just on the latest version of each package ID published up to that point in time? That would make likely make spikes this this only trend upward (instead of up then down again). My guess is this was a some mega push by Microsoft or something like that.
![image](https://user-images.githubusercontent.com/94054/122654527-f674ff80-d100-11eb-99a4-a44260e8092c.png)


Do you know how Power BI would authenticate with our internal Kusto cluster? Right now Insights has entirely automatic secret rotation. It would be ideal to keep that but certainly not a hard requirement.

**Comment by loic-sharma** [comment]
> what do you think about focusing just on the latest version of each package ID published up to that point in time instead of just packages published during that month?

Yup that makes sense, this gives a better sense of where the ecosystem is at instead of what authors are doing at that specific point in time.
